repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        name: Run pylint
        language: python
        types: [python]
        files: ^packages/|^ui/
        exclude: ^packages/.*/tests/

