[tool.poetry]
name = "f1-api-server"
version = "0.1.0"
description = "FastAPI backend for F1 analyzer"
authors = ["Rohith Ravindranath <rohithravin@gmail.com>"]
readme = "README.md"
packages = [{include = "f1_api_server", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11"
fastapi = "^0.116.1"
uvicorn = "^0.35.0"
fastf1_extractor = { path = "../fastf1_extractor" }

[tool.poetry.group.dev.dependencies]
httpx = "^0.28.1"
pytest = "^8.4.1"
pytest-cov = "^6.2.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
